name: deploy
on: 
  push:
    branches:
      - dev
      - issue-100-deploy-to-production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.SSH_HOST }}
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Deploy with rsync
        run: rsync -avz ./ deployer@${{ secrets.SSH_HOST }}:/home/deployer/ddueruem-web/
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: deployer
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd ddueruem-web
            cp ~/.env backend/ddueruemweb/env.production
            docker-compose up -d --build